# Sử dụng Node.js phiên bản ổn định
FROM node:20-alpine

# Đặt thư mục làm việc trong container
WORKDIR /usr/src/app

# Sao chép package.json và package-lock.json để cài đặt dependencies
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ mã nguồn vào container
COPY . .

# Mở cổng Express
EXPOSE 5000

# Chạy lệnh dev (nodemon)
CMD ["npm", "run", "dev"]